version: '3.8'

services:
  redis-master:
    image: redis:6.2
    container_name: redis-master
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

  redis-replica-1:
    image: redis:6.2
    container_name: redis-replica-1
    ports:
      - "6380:6379"
    command: ["redis-server", "--appendonly", "yes", "--replicaof", "redis-master", "6379"]

  redis-replica-2:
    image: redis:6.2
    container_name: redis-replica-2
    ports:
      - "6381:6379"
    command: ["redis-server", "--appendonly", "yes", "--replicaof", "redis-master", "6379"]

#  redis-sentinel-1:
#    image: redis:6.2
#    container_name: redis-sentinel-1
#    ports:
#      - "26379:26379"
#    command: >
#      bash -c "echo 'port 26379' > /etc/redis/sentinel.conf
#               && echo 'sentinel monitor mymaster redis-master 6379 2' >> /etc/redis/sentinel.conf
#               && echo 'sentinel down-after-milliseconds mymaster 5000' >> /etc/redis/sentinel.conf
#               && echo 'sentinel failover-timeout mymaster 60000' >> /etc/redis/sentinel.conf
#               && echo 'sentinel parallel-syncs mymaster 1' >> /etc/redis/sentinel.conf
#               && redis-server /etc/redis/sentinel.conf --sentinel"
#
#  redis-sentinel-2:
#    image: redis:6.2
#    container_name: redis-sentinel-2
#    ports:
#      - "26380:26379"
#    command: >
#      bash -c "echo 'port 26379' > /etc/redis/sentinel.conf
#               && echo 'sentinel monitor mymaster redis-master 6379 2' >> /etc/redis/sentinel.conf
#               && echo 'sentinel down-after-milliseconds mymaster 5000' >> /etc/redis/sentinel.conf
#               && echo 'sentinel failover-timeout mymaster 60000' >> /etc/redis/sentinel.conf
#               && echo 'sentinel parallel-syncs mymaster 1' >> /etc/redis/sentinel.conf
#               && redis-server /etc/redis/sentinel.conf --sentinel"
#
#  redis-sentinel-3:
#    image: redis:6.2
#    container_name: redis-sentinel-3
#    ports:
#      - "26381:26379"
#    command: >
#      bash -c "echo 'port 26379' > /etc/redis/sentinel.conf
#               && echo 'sentinel monitor mymaster redis-master 6379 2' >> /etc/redis/sentinel.conf
#               && echo 'sentinel down-after-milliseconds mymaster 5000' >> /etc/redis/sentinel.conf
#               && echo 'sentinel failover-timeout mymaster 60000' >> /etc/redis/sentinel.conf
#               && echo 'sentinel parallel-syncs mymaster 1' >> /etc/redis/sentinel.conf
#               && redis-server /etc/redis/sentinel.conf --sentinel"

networks:
  default:
    driver: bridge
