version: "3.7"

services:
  zk:
    image: zookeeper:3.4.9
    hostname: zk
    restart: unless-stopped
    ports:
      - "${ZOOKEEPER_PORT}:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=footprint-zoo:2888:3888
    volumes:
      - '../../../../hlidskjalf-volumes/zoo/data:/data'
      - '../../../../hlidskjalf-volumes/zoo/datalog:/datalog'
    networks:
      - hlidskjalf

  ch-1-1:
    image: bitnami/clickhouse:24
    hostname: ch-1-1
    restart: unless-stopped
    environment:
      CLICKHOUSE_ADMIN_USER: yumiko
      CLICKHOUSE_ADMIN_PASSWORD: Yumiko1@
    volumes:
      - '../../../../hlidskjalf-volumes/ch-1-1:/bitnami/clickhouse'
      - './configs/ch-1-1.xml:/etc/clickhouse-server/config.d/config.xml'
    ulimits:
      nofile: 262144
    ports:
      - '${CLICKHOUSE_HTTP_PORT}:8123'
      - '${CLICKHOUSE_TCP_PORT}:9000'
    networks:
      - hlidskjalf

  ch-1-2:
    image: bitnami/clickhouse:24
    hostname: ch-1-2
    restart: unless-stopped
    environment:
      CLICKHOUSE_ADMIN_USER: yumiko
      CLICKHOUSE_ADMIN_PASSWORD: Yumiko1@
    volumes:
      - '../../../../hlidskjalf-volumes/ch-1-2:/bitnami/clickhouse'
      - './configs/ch-1-2.xml:/etc/clickhouse-server/config.d/config.xml'
    ulimits:
      nofile: 262144
#    ports:
#      - '9001:9000'
    networks:
      - hlidskjalf

  ch-2-1:
    image: bitnami/clickhouse:24
    hostname: ch-2-1
    restart: unless-stopped
    environment:
      CLICKHOUSE_ADMIN_USER: yumiko
      CLICKHOUSE_ADMIN_PASSWORD: Yumiko1@
    volumes:
      - '../../../../hlidskjalf-volumes/ch-2-1:/bitnami/clickhouse'
      - './configs/ch-2-1.xml:/etc/clickhouse-server/config.d/config.xml'
#    ports:
#      - '9002:9000'
    ulimits:
      nofile: 262144
    networks:
      - hlidskjalf

  ch-2-2:
    image: bitnami/clickhouse:24
    hostname: ch-2-2
    restart: unless-stopped
    environment:
      CLICKHOUSE_ADMIN_USER: yumiko
      CLICKHOUSE_ADMIN_PASSWORD: Yumiko1@
    volumes:
      - '../../../../hlidskjalf-volumes/ch-2-2:/bitnami/clickhouse'
      - './configs/ch-2-2.xml:/etc/clickhouse-server/config.d/config.xml'
#    ports:
#      - '9003:9000'
    ulimits:
      nofile: 262144
    networks:
      - hlidskjalf

networks:
  hlidskjalf:
    driver: bridge
