workspace(name = "elysium")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Load the Go rules
http_archive(
    name = "io_bazel_rules_go",
    urls = ["https://github.com/bazelbuild/rules_go/releases/download/v0.39.0/rules_go-v0.39.0.tar.gz"],
    sha256 = "05f3abf2727e9b8b59b07e12083c3ccba7a98c29299c7c7e704ab70e0e39cdae",
)

# Load the Gazelle dependency
http_archive(
    name = "bazel_gazelle",
    urls = ["https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.26.0/bazel-gazelle-v0.26.0.tar.gz"],
    sha256 = "7d33c88c2d72b4765aa2f64690dd8c5e5b58a204f4d89b3c330aedc5045dc8a5",
)

load("@io_bazel_rules_go//go:deps.bzl", "go_rules_dependencies", "go_register_toolchains")

go_rules_dependencies()
go_register_toolchains()

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")

gazelle_dependencies()

# Load the Docker rules
http_archive(
    name = "io_bazel_rules_docker",
    urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.24.0/rules_docker-v0.24.0.tar.gz"],
    sha256 = "5a83102a3ffdc07ff3ff4b11da4a9e8c3b9cf4483bcf0e0b24f71a3c96a21309",
)

load("@io_bazel_rules_docker//container:container.bzl", "container_repositories")

container_repositories()
