// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: mockers/faux/service.proto

package api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on FauxRequest with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *FauxRequest) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// FauxRequestValidationError is the validation error returned by
// FauxRequest.Validate if the designated constraints aren't met.
type FauxRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FauxRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FauxRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FauxRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FauxRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FauxRequestValidationError) ErrorName() string { return "FauxRequestValidationError" }

// Error satisfies the builtin error interface
func (e FauxRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFauxRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FauxRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FauxRequestValidationError{}

// Validate checks the field values on Primary with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Primary) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for First

	// no validation rules for Second

	// no validation rules for Third

	// no validation rules for Fourth

	// no validation rules for Fifth

	// no validation rules for Sixth

	// no validation rules for Seventh

	// no validation rules for Eighth

	// no validation rules for Ninth

	// no validation rules for Tenth

	return nil
}

// PrimaryValidationError is the validation error returned by Primary.Validate
// if the designated constraints aren't met.
type PrimaryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PrimaryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PrimaryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PrimaryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PrimaryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PrimaryValidationError) ErrorName() string { return "PrimaryValidationError" }

// Error satisfies the builtin error interface
func (e PrimaryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPrimary.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PrimaryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PrimaryValidationError{}

// Validate checks the field values on Stat with the rules defined in the proto
// definition for this message. If any rules are violated, an error is returned.
func (m *Stat) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for First

	// no validation rules for Second

	// no validation rules for Third

	// no validation rules for Fourth

	// no validation rules for Fifth

	for idx, item := range m.GetPrimaries() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return StatValidationError{
					field:  fmt.Sprintf("Primaries[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// StatValidationError is the validation error returned by Stat.Validate if the
// designated constraints aren't met.
type StatValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StatValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StatValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StatValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StatValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StatValidationError) ErrorName() string { return "StatValidationError" }

// Error satisfies the builtin error interface
func (e StatValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStat.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StatValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StatValidationError{}

// Validate checks the field values on FauxResponse with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *FauxResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Code

	// no validation rules for Message

	if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return FauxResponseValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// FauxResponseValidationError is the validation error returned by
// FauxResponse.Validate if the designated constraints aren't met.
type FauxResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FauxResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FauxResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FauxResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FauxResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FauxResponseValidationError) ErrorName() string { return "FauxResponseValidationError" }

// Error satisfies the builtin error interface
func (e FauxResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFauxResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FauxResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FauxResponseValidationError{}

// Validate checks the field values on FauxResponse_Data with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *FauxResponse_Data) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetStats() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return FauxResponse_DataValidationError{
					field:  fmt.Sprintf("Stats[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// FauxResponse_DataValidationError is the validation error returned by
// FauxResponse_Data.Validate if the designated constraints aren't met.
type FauxResponse_DataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FauxResponse_DataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FauxResponse_DataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FauxResponse_DataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FauxResponse_DataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FauxResponse_DataValidationError) ErrorName() string {
	return "FauxResponse_DataValidationError"
}

// Error satisfies the builtin error interface
func (e FauxResponse_DataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFauxResponse_Data.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FauxResponse_DataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FauxResponse_DataValidationError{}
