repositories:
  - name: dagster
    url: https://dagster-io.github.io/helm

releases:
  - name: dagster
    namespace: hlidskjalf
    createNamespace: true
    chart: dagster/dagster
    version: 1.13.10
    wait: true
    timeout: 600
    values:
      - values.yaml
      - values.secret.yaml
