apiVersion: apps/v1
kind: Deployment
metadata:
  name: authenticator
  namespace: elysium
spec:
  replicas: 3
  selector:
    matchLabels:
      app: authenticator
  template:
    metadata:
      labels:
        app: authenticator
    spec:
      containers:
        - name: authenticator
          image: yumikokawaii/authenticator:latest
          args:
            - "serve"
          ports:
            - containerPort: 8081
            - containerPort: 8080
          env:
            - name: HTTP_PORT
              value: "8080"
            - name: GRPC_PORT
              value: "8081"
            - name: MYSQL_USERNAME
              value: yumiko
            - name: MYSQL_PASSWORD
              value: Yumiko1@
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: elysium
            - name: REDIS_ADDRESS
              value: redis-master:6379
            - name: API_KEY_MAP_CONFIG_PATH
              value: /user
            - name: HASH_KEY
              value: "123"
            - name: ENCRYPT_KEY
              value: YumikoYumiko1234
            - name: OPERATE_INTERVAL_IN_SEC
              value: "300"
