apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-workers
  labels:
    app: locust
    role: workers
spec:
  replicas: 4
  selector:
    matchLabels:
      app: locust
      role: workers
  template:
    metadata:
      labels:
        app: locust
        role: workers
    spec:
      containers:
        - name: locust
          image: locustio/locust
          args:
            [
              "--worker",
              "--master-host",
              "locust-master",
              "-f",
              "/mnt/locust/locustfile.py",
            ]
          ports:
            - containerPort: 8089
          env:
            - name: LOCUST_MODE
              value: worker
          volumeMounts:
            - name: locustfile-volume
              mountPath: /mnt/locust
      volumes:
        - name: locustfile-volume
          configMap:
            name: locust-script
