apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: elysium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: yumikokawaii/users:latest          
          ports:            
            - containerPort: 80            
            - containerPort: 443
          env:
            - name: HTTP_PORT
              value: "80"
            - name: GRPC_PORT
              value: "443"
            - name: MYSQL_USERNAME
              value: yumiko
            - name: MYSQL_PASSWORD
              value: "Yumiko1@"
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: elysium            
