apiVersion: v1
kind: Service
metadata:
  name: users
  namespace: elysium
spec:
  selector:
    app: users
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    - protocol: TCP
      port: 8081
      targetPort: 8081    
  type: LoadBalancer
