image:
  repository: docker.io/yumikokawaii/acoustics
  tag: "49101f3"

host: acoustics.example.com

reloader: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

config:
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
  ERROR_EMITTER__INTERVAL: "1"
