image:
  repository: docker.io/yumikokawaii/acoustics
  tag: "4dfcb5d"

host: acoustics.example.com

reloader: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

config:
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
  ERROR_EMITTER__INTERVAL: "1"
  ERROR_RATE: "0.5"
  RANDOM_DELAY__BASE: "200000000"
  RANDOM_DELAY__RATE: "0.1"
  RANDOM_DELAY__VALUE: "100000000"
  TRIGGER: "1"
