image:
  repository: docker.io/yumikokawaii/bifrost
  tag: "7ea585f"

host: bifrost.example.com

service:
  type: "ClusterIP"

reloader: true

networkPolicy:
  enabled: true
  allowedSources:
    - app: trigger
    - app: echo

replicas: 0

probes:
  port: "http"

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 512Mi

serviceAccount:
  create: true

config:
  ENVIRONMENT: "production"
  LOG_LEVEL: "debug"