image:
  repository: docker.io/yumikokawaii/bifrost
  tag: "641ecb7"

host: bifrost.example.com

service:
  type: "ClusterIP"

reloader: true

replicas: 1

probes:
  port: "http"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

serviceAccount:
  create: true

config:
  ENVIRONMENT: "production"
  LOG_LEVEL: "debug"