image:
  repository: docker.io/yumikokawaii/echo
  tag: "a71fb5c"

host: echo.example.com

annotations:
  bifrost.io/port: "10080"
  bifrost.io/prefixes: '["/api/v1/charge","/api/v1/discharge"]'

service:
  type: "ClusterIP"
  clusterIP: "None"

reloader: true

replicas: 3

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

sidecar:
  enabled: true
  image:
    repository: docker.io/yumikokawaii/skidbladnir
    tag: "a742d69"
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

config:
  ENVIRONMENT: "production"
  LOG_LEVEL: "debug"
  SKIDBLADNIR_SERVER__HTTP: "0.0.0.0:15001"
  ACOUSTICS__ENDPOINT: "http://bifrost:10080"
  ACOUSTICS__PROTOCOL: "http"
  ERROR_EMITTER__INTERVAL: "5"
  ERROR_RATE: "0.5"
  RANDOM_DELAY__BASE: "200000000"
  RANDOM_DELAY__RATE: "0.01"
  RANDOM_DELAY__VALUE: "100000000"
