image:
  repository: docker.io/yumikokawaii/echo
  tag: "a71fb5c"

host: echo.example.com

annotations:
  bifrost.io/port: "10443"
  bifrost.io/prefixes: '["/echo.Echo"]'

service:
  type: "ClusterIP"
  clusterIP: "None"

reloader: true

replicas: 3

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

config:
  ENVIRONMENT: "production"
  LOG_LEVEL: "debug"
  ACOUSTICS__ENDPOINT: "bifrost:10443"
  ACOUSTICS__PROTOCOL: "grpc"
  TRIGGER: "2"
  ERROR_EMITTER__INTERVAL: "5"
  ERROR_RATE: "0.5"
  RANDOM_DELAY__BASE: "200000000"
  RANDOM_DELAY__RATE: "0.01"
  RANDOM_DELAY__VALUE: "100000000"
