image:
  repository: docker.io/yumikokawaii/echo
  tag: "df9068b"

host: echo.example.com

annotations:
  bifrost.io/port: "10080"
  bifrost.io/prefixes: '["/api/v1/charge","/api/v1/discharge"]'

service:
  type: "ClusterIP"
  clusterIP: "None"

reloader: true

networkPolicy:
  enabled: true
  allowedSources:
    - app: bifrost

replicas: 3

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

sidecar:
  enabled: true
  image:
    repository: docker.io/yumikokawaii/skidbladnir
    tag: "55fef3d"
  ports:
    outbound: 15001
    inboundGrpc: 15002
    inboundHttp: 15003
    appGrpc: 10443
    appHttp: 10080
    leaderGrpc: 15443
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

config:
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
  SKIDBLADNIR_SERVER__HTTP: "0.0.0.0:15001"
  SKIDBLADNIR_SERVER__GRPC: "0.0.0.0:15443"
  OUTBOUND__PORT: "15001"
  INBOUND__GRPC__ENDPOINT: "0.0.0.0:15002"
  INBOUND__GRPC__TARGET_PORT: "10443"
  INBOUND__HTTP__ENDPOINT: "0.0.0.0:15003"
  INBOUND__HTTP__TARGET_PORT: "10080"
  ACOUSTICS__ENDPOINT: "http://bifrost:10080"
  ACOUSTICS__PROTOCOL: "http"
  ERROR_EMITTER__INTERVAL: "5"
  ERROR_RATE: "0"
  RANDOM_DELAY__BASE: "200000000"
  RANDOM_DELAY__RATE: "0.01"
  RANDOM_DELAY__VALUE: "100000000"
  SERVICE: "echo"
  NAMESPACE: "hlidskjalf"
  LIMITER__ENABLED: true
  LIMITER__RPS: "100"
  LIMITER__BURST: "100"
  LIMITER__LEADER_PORT: "15443"
