image:
  repository: docker.io/yumikokawaii/trigger
  tag: "eb068f6"

host: trigger.example.com

service:
  type: "ClusterIP"

reloader: true

replicas: 5

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

sidecar:
  enabled: true
  image:
    repository: docker.io/yumikokawaii/skidbladnir
    tag: "latest"
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

config:
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
  ACOUSTICS__ENDPOINT: "http://bifrost:10443"
  ACOUSTICS__PROTOCOL: "http"
  ECHO__ENDPOINT: "http://bifrost:10443"
  ECHO__PROTOCOL: "http"
  CHAOS__INTERVAL: "100000" # 0.1ms