apiVersion: apps/v1
kind: Deployment
metadata:
  name: presentation
  namespace: elysium
spec:
  replicas: 3
  selector:
    matchLabels:
      app: presentation
  template:
    metadata:
      labels:
        app: presentation
    spec:
      containers:
        - name: presentation
          image: yumikokawaii/presentation:latest
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          ports:
            - containerPort: 80
            - containerPort: 443
          env:
            - name: HTTP_PORT
              value: "80"
            - name: GRPC_PORT
              value: "443"
            - name: ECHO_HOST
              value: echo:443
            - name: FAUX_HOST
              value: faux:443
            - name: FICTIO_HOST
              value: fictio:443
            - name: MIMIC_HOST
              value: mimic:443
            - name: VIRTUAL_HOST
              value: virtual:443
            - name: USE_GRPC_PROTOCOL
              value: "TRUE"
            - name: SKIP_MARSHAL_RESPONSE
              value: "TRUE"
            - name: TRAFFIC_DELAY_IN_MILLI_SEC
              value: "200"
