version: "3.7"

services:
  docker-registry:
    image: bitnami/harbor-registry
    restart: unless-stopped
    container_name: docker-registry
#    networks:
#      - registry-network
#    ports:
#      - 8001:80
#      - 5000:5000
    network_mode: host
    volumes:
      #- '${VOLUME_FOLDER}/registry:/harbor-registry'
      - ${HARBOR_CONFIG_FOLDER}:/etc/registry

networks:
  registry-network:
    driver: bridge
