// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// PawnServiceClient is the client API for PawnService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PawnServiceClient interface {
	Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error)
}

type pawnServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPawnServiceClient(cc grpc.ClientConnInterface) PawnServiceClient {
	return &pawnServiceClient{cc}
}

func (c *pawnServiceClient) Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error) {
	out := new(GreetResponse)
	err := c.cc.Invoke(ctx, "/pawn.api.PawnService/Greet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PawnServiceServer is the server API for PawnService service.
// All implementations must embed UnimplementedPawnServiceServer
// for forward compatibility
type PawnServiceServer interface {
	Greet(context.Context, *GreetRequest) (*GreetResponse, error)
	mustEmbedUnimplementedPawnServiceServer()
}

// UnimplementedPawnServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPawnServiceServer struct {
}

func (UnimplementedPawnServiceServer) Greet(context.Context, *GreetRequest) (*GreetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Greet not implemented")
}
func (UnimplementedPawnServiceServer) mustEmbedUnimplementedPawnServiceServer() {}

// UnsafePawnServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PawnServiceServer will
// result in compilation errors.
type UnsafePawnServiceServer interface {
	mustEmbedUnimplementedPawnServiceServer()
}

func RegisterPawnServiceServer(s grpc.ServiceRegistrar, srv PawnServiceServer) {
	s.RegisterService(&_PawnService_serviceDesc, srv)
}

func _PawnService_Greet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PawnServiceServer).Greet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pawn.api.PawnService/Greet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PawnServiceServer).Greet(ctx, req.(*GreetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PawnService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pawn.api.PawnService",
	HandlerType: (*PawnServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greet",
			Handler:    _PawnService_Greet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pawn/service.proto",
}
