apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ if and .Values.service .Values.service.type }}{{ .Values.service.type }}{{ else }}ClusterIP{{ end }}
  {{- if and .Values.service .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: grpc
      port: 10443
      targetPort: grpc
      protocol: TCP
    - name: http
      port: 10080
      targetPort: http
      protocol: TCP
