apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- $serviceType := "ClusterIP" }}
  {{- if and .Values.service .Values.service.type }}
  {{- $serviceType = .Values.service.type }}
  {{- end }}
  type: {{ $serviceType }}
  {{- if eq $serviceType "None" }}
  clusterIP: None
  {{- end }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: grpc
      port: 10443
      targetPort: grpc
      protocol: TCP
    - name: http
      port: 10080
      targetPort: http
      protocol: TCP
