{{- $createSA := false }}
{{- if and .Values.serviceAccount .Values.serviceAccount.create }}
{{- $createSA = true }}
{{- end }}
{{- if and .Values.sidecar .Values.sidecar.enabled }}
{{- $createSA = true }}
{{- end }}
{{- if $createSA }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
{{- end }}
