apiVersion: v1
kind: Service
metadata:
  name: interactions
  namespace: elysium
spec:
  selector:
    app: interactions
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: grpc
      protocol: TCP
      port: 8081
      targetPort: 8081    
  type: LoadBalancer
