apiVersion: v1
kind: Service
metadata:
  name: interactions
  namespace: elysium
spec:
  selector:
    app: interactions
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80      
    - name: grpc
      protocol: TCP
      port: 443
      targetPort: 443
  type: ClusterIP
