apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual
  namespace: elysium
spec:
  replicas: 3
  selector:
    matchLabels:
      app: virtual
  template:
    metadata:
      labels:
        app: virtual
    spec:
      containers:
        - name: virtual
          image: yumikokawaii/virtual:latest
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80
            - containerPort: 443
          env:
            - name: HTTP_PORT
              value: "80"
            - name: GRPC_PORT
              value: "443"
            - name: STATS_RANGE_LOWER
              value: "10"
            - name: STATS_RANGE_UPPER
              value: "20"
            - name: STRING_RANGE_LOWER
              value: "100"
            - name: STRING_RANGE_UPPER
              value: "500"
            - name: PRIMARY_RANGE_LOWER
              value: "5"
            - name: PRIMARY_RANGE_UPPER
              value: "10"
            - name: SECONDARY_RANGE_LOWER
              value: "5"
            - name: SECONDARY_RANGE_UPPER
              value: "10"
            - name: TERTIARY_RANGE_LOWER
              value: "5"
            - name: TERTIARY_RANGE_UPPER
              value: "10"
            - name: QUATERNARY_RANGE_LOWER
              value: "5"
            - name: QUATERNARY_RANGE_UPPER
              value: "10"
            - name: ENABLE_TRAFFIC_DELAY
              value: "FALSE"
            - name: TRAFFIC_DELAY_IN_MILLI_SEC
              value: "200"
