apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimic
  namespace: elysium
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mimic
  template:
    metadata:
      labels:
        app: mimic
    spec:
      containers:
        - name: mimic
          image: yumikokawaii/mimic:latest
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          ports:
            - containerPort: 80
            - containerPort: 443
          env:
            - name: HTTP_PORT
              value: "80"
            - name: GRPC_PORT
              value: "443"
            - name: STATS_RANGE_LOWER
              value: "10"
            - name: STATS_RANGE_UPPER
              value: "20"
            - name: STRING_RANGE_LOWER
              value: "100"
            - name: STRING_RANGE_UPPER
              value: "500"
            - name: PRIMARY_RANGE_LOWER
              value: "10"
            - name: PRIMARY_RANGE_UPPER
              value: "20"
            - name: SECONDARY_RANGE_LOWER
              value: "10"
            - name: SECONDARY_RANGE_UPPER
              value: "20"
            - name: TERTIARY_RANGE_LOWER
              value: "10"
            - name: TERTIARY_RANGE_UPPER
              value: "20"
            - name: ENABLE_TRAFFIC_DELAY
              value: "FALSE"
            - name: TRAFFIC_DELAY_IN_MILLI_SEC
              value: "200"
