apiVersion: v1
kind: Service
metadata:
  name: mimic
  namespace: elysium
spec:
  type: ClusterIP
  selector:
    app: mimic  
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80            
    - name: grpc
      protocol: TCP
      port: 443
      targetPort: 443            
