CREATE TABLE `interactions`
(
    `id`         INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `post_id`    INT UNSIGNED NOT NULL,
    `author`     VARCHAR(255) NOT NULL,
    `type`       VARCHAR(255) NOT NULL,
    `content`    TEXT         NOT NULL,
    `created_at` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;