apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
  labels:
    app: locust
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
      role: master
  template:
    metadata:
      labels:
        app: locust
        role: master
    spec:
      containers:
        - name: locust
          image: locustio/locust
          args: ["--master", "-f", "/mnt/locust/locustfile.py"]
          ports:
            - containerPort: 8089
            - containerPort: 5557
          env:
            - name: LOCUST_MODE
              value: master
          volumeMounts:
            - name: locustfile-volume
              mountPath: /mnt/locust
      volumes:
        - name: locustfile-volume
          configMap:
            name: locust-script
