apiVersion: v1
kind: Service
metadata:
  name: locust-master
  labels:
    app: locust
    role: master
spec:
  type: ClusterIP
  ports:
    - name: interface
      port: 8089
      targetPort: 8089
    - name: tcp
      port: 5557
      targetPort: 5557
  selector:
    app: locust
    role: master
