apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts
  namespace: elysium
spec:
  replicas: 3
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: yumikokawaii/posts:latest          
          ports:            
            - containerPort: 80            
            - containerPort: 443
          env:
            - name: HTTP_PORT
              value: "80"
            - name: GRPC_PORT
              value: "443"
            - name: MYSQL_USERNAME
              value: yumiko
            - name: MYSQL_PASSWORD
              value: "Yumiko1@"
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: elysium            
