version: "3.8"

services:
  master:
    image: locustio/locust
    hostname: benchmark-master-1
    network_mode: host
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master

#  worker:
#    image: locustio/locust
#    network_mode: host
#    volumes:
#      - ./:/mnt/locust
#    command: -f /mnt/locust/locustfile.py --worker --master-host benchmark-master-1

#  worker2:
#    image: locustio/locust
#    volumes:
#      - ./locustfile.py:/mnt/locustfile.py
#    command: >
#      locust -f /mnt/locustfile.py --worker --master-host master --master-port 5557
#
#  worker3:
#    image: locustio/locust
#    volumes:
#      - ./locustfile.py:/mnt/locustfile.py
#    command: >
#      locust -f /mnt/locustfile.py --worker --master-host master --master-port 5557
#
#  worker4:
#    image: locustio/locust
#    volumes:
#      - ./locustfile.py:/mnt/locustfile.py
#    command: >
#      locust -f /mnt/locustfile.py --worker --master-host master --master-port 5557
