apiVersion: apps/v1
kind: Deployment
metadata:
  name: center
  namespace: elysium
spec:
  replicas: 3
  selector:
    matchLabels:
      app: center
  template:
    metadata:
      labels:
        app: center
    spec:
      containers:
        - name: center
          image: yumikokawaii/center:latest          
          ports:            
            - containerPort: 8080            
            - containerPort: 8081
          env:
            - name: HTTP_PORT
              value: "8080"
            - name: GRPC_PORT
              value: "8081"
            - name: INTERACTION_SERVICE_HOST
              value: interactions:443
            - name: POST_SERVICE_HOST
              value: posts:443
            - name: USER_SERVICE_HOST
              value: users:443
            - name: AUTHENTICATOR_HOST
              value: authenticator:443
            - name: USE_GRPC_PROTOCOL
              value: "TRUE"       
