apiVersion: v1
kind: Service
metadata:
  name: center
  namespace: elysium
spec:
  selector:
    app: center
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: grpc
      protocol: TCP
      port: 8081
      targetPort: 8081  
      nodePort: 30443
  type: NodePort
