apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: elysium
spec:
  type: ClusterIP
  selector:
    app: echo
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: grpc
      protocol: TCP
      port: 443
      targetPort: 443
