name: publish pawn image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: login docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: extract image tag
        id: vars
        run: echo "IMAGE_TAG=${GITHUB_SHA::6}" >> $GITHUB_ENV

      - name: build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./elysium/dockerfiles/pawn.dockerfile
          push: true
          tags: |
            yumikokawaii/pawn:${{env.IMAGE_TAG}}
            yumikokawaii/pawn:latest